// export const ADD_PROJECT = "ADD_PROJECT";
// export const EDIT_PROJECT = "EDIT_PROJECT";

export const LIFT_TOKEN_TO_STATE = "LIFT_TOKEN_TO_STATE"

export const LOGOUT = "LOGOUT"

export const LIFT_PROJECT_TO_STATE = "LIFT_PROJECT_TO_STATE"
export const LIFT_ALL_PROJECTS_TO_STATE = "LIFT_ALL_PROJECTS_TO_STATE"
